### ISSUE TITLE
Server Browser Map Tooltip

### ISSUE THREAD

**Issue by takempf** [Fauntleroy/openra-web#2]
Just creating an issue so I can keep track of my todos.

### Todos

- [x] fix issue where tooltip appears below "no build here" bg
- [x] fix issue where tooltip does not go away when leaving the table
- [x] Make player list scroll vertically (marquee-style) if it is too tall ("too tall" tbd)

**Comment by takempf** [comment]
Tooltips can escape
<img width="742" alt="image" src="https://user-images.githubusercontent.com/507047/91383499-20131200-e7e1-11ea-9779-cdc8e46061f0.png">
