### ISSUE TITLE
Feedback / Acceptance checklist

### ISSUE THREAD

**Issue by takempf** [Fauntleroy/openra-web#3]
- [x] fix all "scanlines" headers
- [x] add Dune 2K logos to bg
- [ ] final "marketing" assets
- [x] final Lighthouse optimizations
- [ ] readme
- [x] normalize "no build here" margins
- [x] give checkboxes + radios focus states
- [x] drop special hover effect for most links
- [x] replace OSX with "macOS"
- [x] normalize button widths when they are next to each other
- [x] more obvious click regions in mobile menu
- [x] brighten bg just a bit
- [ ] address CSS concerns in some way
- [ ] component-ize a couple things here and there
- [x] xml / rss feeds
- [x] ensure reduced motion is handled throughout
